/*
 * Copyright (c) 2013 L2jMobius
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
 * IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package org.l2jmobius.gameserver.ai;

import org.l2jmobius.gameserver.model.actor.enums.npc.MonsterArchetype;

/**
 * A set of weighted biases that scale the existing dice-rolls inside {@link AttackableAI}.
 * <p>
 * This is deliberately NOT a new decision-making engine: it never adds capabilities a monster didn't already have (it can't make a monster cast a skill it doesn't own, for example). It only scales the probabilities and thresholds already present in the stock AI, so every archetype is just a
 * different "seasoning" on the same underlying mechanics - safe to layer on top of live content without invalidating existing balance work.
 * <p>
 * All fields are multipliers/thresholds applied against the original stock constant at the call site; a value of {@code 1.0} (or the archetype-appropriate neutral value) reproduces stock behavior exactly.
 * @author Zoey76
 */
public class AIProfile
{
	/** HP% (0..1) below which the flee/fear behavior can trigger. Stock value is 0.15. */
	public final float fleeHpThreshold;
	/** Multiplier on the per-tick chance to actually flee once under the HP threshold. */
	public final float fleeChanceScale;
	/** Multiplier on the chance to cast a self-heal skill. */
	public final float selfHealBias;
	/** Multiplier on the chance to heal/buff/resurrect clan allies. */
	public final float allySupportBias;
	/** Multiplier on the chance to bother casting a general-purpose skill at all. */
	public final float castFrequencyBias;
	/** Multiplier on the archer kiting-away chance when a target gets too close. */
	public final float meleeRetreatBias;
	/** How much angrier (extra hate) the monster gets as its own HP drops. 0 = no rage. */
	public final float rageOnLowHp;
	/** Multiplier applied to hate generated by whoever is currently attacking this monster. */
	public final float vengeanceBias;
	/** Divisor against the raid/grand-boss/minion "change target" chaos roll; higher = stickier. */
	public final float targetSwitchResistance;
	/** Divisor against the chance to forget its aggro list once healed back to full. */
	public final float persistenceBias;
	
	private AIProfile(float fleeHpThreshold, float fleeChanceScale, float selfHealBias, float allySupportBias, float castFrequencyBias, float meleeRetreatBias, float rageOnLowHp, float vengeanceBias, float targetSwitchResistance, float persistenceBias)
	{
		this.fleeHpThreshold = fleeHpThreshold;
		this.fleeChanceScale = fleeChanceScale;
		this.selfHealBias = selfHealBias;
		this.allySupportBias = allySupportBias;
		this.castFrequencyBias = castFrequencyBias;
		this.meleeRetreatBias = meleeRetreatBias;
		this.rageOnLowHp = rageOnLowHp;
		this.vengeanceBias = vengeanceBias;
		this.targetSwitchResistance = targetSwitchResistance;
		this.persistenceBias = persistenceBias;
	}
	
	// @formatter:off
	//                                                    			 fleeHp fleeChance selfHeal allySupport castFreq meleeRetreat rageOnLowHp vengeance switchRes persistence
	private static final AIProfile BALANCED_PROFILE   = new AIProfile(0.15f, 2.0f,   	1.0f,    1.0f,       1.0f,    1.0f,        0.0f,       1.0f,     1.0f,     1.0f);
	private static final AIProfile AGGRESSIVE_PROFILE = new AIProfile(0.00f, 0.0f,   	0.6f,    0.5f,       0.9f,    0.4f,        3.3f,       1.1f,     1.3f,     2.0f);
	private static final AIProfile COWARD_PROFILE     = new AIProfile(0.50f, 5.0f,   	1.7f,    0.6f,       0.7f,    4.2f,        0.0f,       0.2f,     0.4f,     0.3f);
	private static final AIProfile SKILLFUL_PROFILE   = new AIProfile(0.15f, 1.0f,   	1.3f,    1.1f,       3.5f,    1.0f,        5.0f,       1.0f,     1.1f,     1.0f);
	private static final AIProfile MAGE_PROFILE       = new AIProfile(0.20f, 3.2f,   	5.4f,    1.0f,       8.2f,    3.5f,        0.0f,       1.0f,     1.0f,     1.0f);
	private static final AIProfile FIGHTER_PROFILE    = new AIProfile(0.08f, 0.4f,   	0.7f,    0.4f,       0.3f,    0.2f,        2.2f,       1.0f,     1.2f,     1.1f);
	private static final AIProfile SUPPORTER_PROFILE  = new AIProfile(0.25f, 3.4f,  	3.0f,    5.5f,       8.8f,    1.6f,        0.0f,       0.7f,     1.0f,     0.8f);
	private static final AIProfile RAGER_PROFILE      = new AIProfile(0.00f, 0.0f,   	0.3f,    0.2f,       1.3f,    0.1f,       15.0f,       1.3f,     1.4f,     2.5f);
	private static final AIProfile AVENGER_PROFILE    = new AIProfile(0.08f, 0.0f,   	0.9f,    0.6f,       1.0f,    0.6f,        5.5f,       6.5f,     3.5f,     1.2f);
	// @formatter:on
	
	/**
	 * @param archetype the archetype to look up, may be {@code null}
	 * @return the immutable, shared profile for the given archetype (never {@code null})
	 */
	public static AIProfile forArchetype(MonsterArchetype archetype)
	{
		if (archetype == null)
		{
			return BALANCED_PROFILE;
		}
		
		switch (archetype)
		{
			case AGGRESSIVE:
			{
				return AGGRESSIVE_PROFILE;
			}
			case COWARD:
			{
				return COWARD_PROFILE;
			}
			case SKILLFUL:
			{
				return SKILLFUL_PROFILE;
			}
			case MAGE:
			{
				return MAGE_PROFILE;
			}
			case FIGHTER:
			{
				return FIGHTER_PROFILE;
			}
			case SUPPORTER:
			{
				return SUPPORTER_PROFILE;
			}
			case RAGER:
			{
				return RAGER_PROFILE;
			}
			case AVENGER:
			{
				return AVENGER_PROFILE;
			}
			default:
			{
				return BALANCED_PROFILE;
			}
		}
	}
}